name: Deploy EC2 Instance on AWS

on:
  push:
    branches:
      - main

jobs:
  deployterraform:
    runs-on: ubuntu-latest
    env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: |
        terraform fmt
        terraform init -upgrade

    - name: Terraform Apply
      run: terraform apply -auto-approve

